spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://120.77.45.136:3306/spring_security?characterEncoding=UTF-8&nullCatalogMeansCurrent=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: springuser
    password: 123456

  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
logging:
  level:
    com:
      connext:
        spring_security:
          dao: info

  #  path: /Spirng/log
  file: log/spring-security.log
  file.max-size: 10MB